spring:
  application:
    name: market
  jpa:
    hibernate:
    ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.hn.market: DEBUG