spring:
    application:
        name: market
    datasource:
        url: jdbc:postgresql://localhost:5434/market
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
        ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
        enabled: true
        change-log: classpath:/db/postgres/changelog/db.changelog-master.xml
    profiles:
        active: dev