spring:
    config:
        import: classpath:/application-dev-common.yml

    datasource:
        url: jdbc:postgresql://localhost:5434/dev_market
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
        change-log: classpath:/db/postgres/changelog/db.changelog-master.xml